---
- name: Configure group directories, files, and permissions
  hosts: server2
  become: yes
  vars:
    base_path: "/team"
    teams:
      - Sales
      - Support
      - Services
      - IT
    special_user: "ctf_sa"

  tasks:
    - name: Ensure base directory exists
      ansible.builtin.file:
        path: "{{ base_path }}"
        state: directory
        mode: '0755'

    - name: Create group directories with proper permissions
      ansible.builtin.file:
        path: "{{ base_path }}/{{ item }}"
        state: directory
        owner: "root"
        group: "{{ item }}"
        mode: '0770'
      loop: "{{ teams }}"

    - name: Create "Salesnumbers" file inside Sales folder
      ansible.builtin.file:
        path: "{{ base_path }}/Sales/Salesnumbers"
        state: touch
        owner: "root"
        group: "Sales"
        mode: '0660'

    - name: Ensure IT tasks.done file exists
      ansible.builtin.file:
        path: "{{ base_path }}/it/tasks.done"
        state: touch
        owner: "root"
        group: "IT"
        mode: '0660'

    - name: Add "all folders are set" to the top of /team/IT/tasks.done
      ansible.builtin.lineinfile:
        path: "{{ base_path }}/it/tasks.done"
        line: "all folders are set"
        insertbefore: BOF

    - name: Ensure IT tasks.done file exists
      ansible.builtin.file:
        path: "/it/tasks.done"
        state: touch
        owner: "root"
        mode: '0660'

    - name: Add "all folders are set" to the top of /team/IT/tasks.done
      ansible.builtin.lineinfile:
        path: "/it/tasks.done"
        line: "all folders are set"
        insertbefore: BOF

    - name: Add ctf_sa to all team groups
      ansible.builtin.user:
        name: "{{ special_user }}"
        groups: "{{ teams | join(',') }}"
        append: yes